# Generated by Django 3.2.8 on 2021-10-27 20:18

from django.db import migrations
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelingpost',
            name='youtubevideo',
            field=embed_video.fields.EmbedVideoField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
