# Generated by Django 3.2.8 on 2021-10-28 06:09

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopage', '0002_travelingpost_youtubevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelingpost',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='travelingpost',
            name='tags',
        ),
        migrations.AlterField(
            model_name='travelingpost',
            name='youtubevideo',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
