# Generated by Django 3.2.8 on 2021-10-28 23:04

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliopage', '0003_auto_20211028_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnowboardingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('sub_headline', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('youtubevideo', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
        ),
    ]
